Week Eight
CodeSpaceHQ/AppliedAlgorithms pull request #20
Opened 2016-11-28 20:41 UTC by NilsG-S

I'm reasonably sure I haven't messed up the repository. Mainly I need feedback on my README and the quality of my code.

2016-11-29 09:56 UTC, asclines requested changes
Always love a PR that starts with:

> I'm reasonably sure I haven't messed up the repository

Overall good. One tiny change request but other than that:
The guide was nice & concise, yet gets all the important information across. I will be revisiting my work on this repo to see if I can't do the same.

Same with the code, very beautiful. I have more of a question than a suggestion; Have you considered using typedefs for common variables like `long long`? It's a habit I picked up for these kind of problems where I'm not 100% going in what data type I will be using. i.e. `int, long, long long,` etc..

While I'm marking this as "request changes", I'm really just wanting a response to this review and it's comment before "approval".

2016-11-29 09:56 UTC, asclines commented on Guide/Greedy/Algorithmic Crush/README.md
> +The naive method to solve this problem involves adding the value of ‘k’ to each element in the list from ‘a’ to ‘b’ inclusively for each of the ‘M’ operations.
Maybe move this to conclusion? You are not implemented the naive method (I hope), so this probably shouldn't be in the Algorithm Overview as this part should be focused on explaining to the user how the implemented algorithm works.

The conclusion would be a good spot to discuss alternative ways to solve the problem and discuss why they are/aren't as efficient as the implemented algorithm

2016-11-29 18:22 UTC, NilsG-S commented
Thanks for the review! You have a good point about moving the discussion of the naive method to the conclusion. I'll make the change and resubmit.

As for why I don't use typedefs; I find that I don't like how they obfuscate the true type of the variable. I've worked with code that used them extensively before, and it was always a pain to go see exactly what the typedef was doing. But there are good and bad ways of using a tool, and as you've said, in this case they could be useful.

2016-11-30 16:55 UTC, asclines approved these changes

2016-11-30 17:41 UTC, merged